"""empty message

Revision ID: 1adcde440e7d
Revises: ee3e6f0f3f99
Create Date: 2024-04-06 20:32:41.568425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1adcde440e7d'
down_revision = 'ee3e6f0f3f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.alter_column('date_started',
               existing_type=sa.DATE(),
               type_=sa.String(length=4),
               existing_nullable=False)
        batch_op.alter_column('date_ended',
               existing_type=sa.DATE(),
               type_=sa.String(length=4),
               existing_nullable=False)

    with op.batch_alter_table('work_experience', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=4),
               existing_nullable=False)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=4),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_experience', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.String(length=4),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.String(length=4),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.alter_column('date_ended',
               existing_type=sa.String(length=4),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('date_started',
               existing_type=sa.String(length=4),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
