"""empty message

Revision ID: 2325ba647ef2
Revises: 
Create Date: 2024-03-24 19:50:44.353083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2325ba647ef2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('user_email', sa.String(length=20), nullable=False),
    sa.Column('email_token', sa.String(length=30), nullable=True),
    sa.Column('password_token', sa.String(length=30), nullable=True),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_email'], ['patient.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    # ### end Alembic commands ###
