"""empty message

Revision ID: 319859dadf79
Revises: 09f591fd7969
Create Date: 2024-03-24 20:28:54.960252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319859dadf79'
down_revision = '09f591fd7969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
