"""empty message

Revision ID: 3460b91b423d
Revises: 8c453b48f15e
Create Date: 2024-04-22 19:15:48.172808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3460b91b423d'
down_revision = '8c453b48f15e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospital', schema=None) as batch_op:
        batch_op.alter_column('phone2',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True)
        batch_op.alter_column('email2',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospital', schema=None) as batch_op:
        batch_op.alter_column('email2',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('phone2',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)

    # ### end Alembic commands ###
