"""empty message

Revision ID: 8c453b48f15e
Revises: d1c27915b730
Create Date: 2024-04-22 16:59:31.037276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c453b48f15e'
down_revision = 'd1c27915b730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospital', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favicon', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('logo', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospital', schema=None) as batch_op:
        batch_op.drop_column('logo')
        batch_op.drop_column('favicon')

    # ### end Alembic commands ###
