"""empty message

Revision ID: 9fe85e8cb9f6
Revises: dacb38b02f52
Create Date: 2024-04-14 13:43:11.884126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9fe85e8cb9f6'
down_revision = 'dacb38b02f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_schedule', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=mysql.TIME(),
               type_=sa.String(length=6),
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=mysql.TIME(),
               type_=sa.String(length=6),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_schedule', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.String(length=6),
               type_=mysql.TIME(),
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.String(length=6),
               type_=mysql.TIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
