"""empty message

Revision ID: d1c27915b730
Revises: 9609782572bf
Create Date: 2024-04-22 16:11:30.314432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1c27915b730'
down_revision = '9609782572bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospital', schema=None) as batch_op:
        batch_op.drop_column('logo')
        batch_op.drop_column('favicon')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospital', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favicon', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('logo', mysql.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
